services:
  - type: web
    name: chatbot
    runtime: node
    rootDir: back

    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      npm install

<<<<<<< HEAD
    startCommand: npm start
=======
    startCommand: npm start
>>>>>>> f70af694bca4ec0b45c033216036b3fc4584d1c2
